blog/urls.py
from django.urls import path, include, re_path
from blog import views


app_name = "blog"

urlpatterns = [
    re_path(r'^login/$',views.user_login, name='user_login'),
    re_path(r'^register/$',views.register, name='register'),
]

vidainteligente/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from blog import views

urlpatterns = [
    re_path(r'^$',views.index, name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^blog/',include('blog.urls')),
    re_path(r'^logout/$',views.user_logout, name = 'logout')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete =models.CASCADE)

    #extra
    portfolio_site = models.URLField(blank=True)    
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from blog.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model=UserProfileInfo
        fields = ('portfolio_site','profile_pic')

blog/views.py
from django.shortcuts import render
from blog.models import UserProfileInfo
from blog.forms import UserForm, UserProfileInfoForm

#for login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

def index(request):
    dict={'name':"Josafat Corona"}
    return render(request,'index.html',context= dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User is not active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} password {}".format(username, password))
            return HttpResponse("Credentianls failed")
    else:
        return render(request,'blog/login.html',{})

def register(request):
    registered = False
    user_form = UserForm(data=request.POST)
    profile_form = UserProfileInfoForm(data=request.POST)
    if request.method == 'POST':
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'blog/register.html',{
                                                'user_form':user_form,
                                                'profile_form':profile_form,
                                                'registered':registered})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/blog/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title_block %}
      {% endblock %}
    </title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <style media="screen">
    .jumbotron {
        padding: 2rem 1rem;
        margin-bottom: 2rem;
        background-color: #e9ecef;
        border-radius: .3rem;
    }
    </style>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">VidaInt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:user_login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'blog:register' %}">Register</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:register' %}" tabindex="-1" >Register</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/blog/login.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
{% block title_block %}
  Login
{% endblock %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Inicia sesión!</h1>
  </div>
  <hr>
  <br>
  <form class="form"  method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder='Username'>
    <hr>
    <label for="password">Password:</label>
    <input type="password" name="password">
    <br>
    <input class="btn btn-primary" type="submit" name="login" value="Login">

  </form>
{% endblock %}

templates/blog/register.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
{% block title_block %}
  Registrar
{% endblock %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Registrate para ser parte de la comunidad!</h1>
    <h3>Un espacio donde podrás encontra información sobre gadgets/tecnología que te harán la vida más fácil, todo por buenos precios.</h3>
    <span>My name is {{name}} and welcome to my blog</span>
  </div>
  <hr>
  <br>
  <div class="row">
    <div class="col-lg-2">

    </div>
    <div class="col-lg-8">
      <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form</h3>
        <form class="form"  method="post">
            {% csrf_token %}
            <div class="mb-3">
              {{ user_form.as_p }}
            </div>
            <hr>
            <div class="mb-3">
              {{ profile_form.as_p }}
            </div>
            <br>
            <input class="btn btn-primary" type="submit" name="" value="Register">
        </form>
        {% endif %}
      </div>
    </div>
    <div class="col-lg-2">

    </div>
  </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}
{% block title_block %}
  Vida Inteligente Blog
{% endblock %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Bienvenidos a Vida Inteligente</h1>
    <h3>Un especio donde podrás encontra información sobre gadgets/tecnología que te harán la vida más fácil, todo por buenos precios.</h3>
    <span>My name is {{name}} and welcome to my blog</span>
  </div>
  <hr>
  <br>
  <div class="row">
    <div class="col-lg-8">
      <h4>Ultimas entradas</h4>
      <img src="{% static "images/smartlife.jpg"%}" alt="Failed">
      <img src="{% static "images/logo_smartlife.png"%}" alt="X">
    </div>
    <div class="col-lg-4">
    <h4>Relacionado</h4>
    <span>Aqui iran otras secciones secundarias</span>
  </div>


  </div>
{% endblock %}